print("<===  ALL CARDS  ====>")
print(Deck.allCards)
print("<=======>")
print(Deck.allCards.shuffle())
print("<===  ALL SPADES  ====>")
print(Deck.allSpades)
print("<=======>")
print(Deck.allSpades.shuffle())
print("<===  ALL CLUBS  ====>")
print(Deck.allClubs)
print("<=======>")
print(Deck.allClubs.shuffle())
print("<===  ALL HEARTS  ====>")
print(Deck.allHearts)
print("<=======>")
print(Deck.allHearts.shuffle())
print("<===  ALL DIAMONDS  ====>")
print(Deck.allDiamonds)
print("<=======>")
print(Deck.allDiamonds.shuffle())