# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day09' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'dvdovenk2018', :git => 'https://gitlab.com/Enzewon/dvdovenk2018.git'

  # Pods for day09

end
